elearning/urls.py
from django.contrib import admin
from django.urls import path
# Use include() to add paths from the catalog application 
from django.urls import include
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from gogoedu.views import change_language
import notifications.urls
import notifications_rest.urls
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views


urlpatterns = [
    path('change_language/', change_language, name='change_language'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('gogoedu/', include('gogoedu.urls')),
    path('memory/', include('memory.urls')),
    path('', RedirectView.as_view(url='gogoedu/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notifications/', include('notifications_rest.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    prefix_default_language=False,
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

memory/urls.py
from django.conf.urls import url

from . import views

app_name = 'memory'
urlpatterns = [
    url(r'^$', views.Welcome.as_view(), name='welcome'),
    url(r'^(?P<urlid>[0-9a-z]+)/$', views.GameView.as_view(), name='game'),
    url(r'^(?P<urlid>[0-9a-z]+)/json$', views.GameViewJSON.as_conditional_view(), name='game_json'),
]

gogoedu/models.py
from os import name
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.db.models.fields import BooleanField
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from PIL import Image
from django.utils import timezone
import datetime
from notifications.signals import notify
from django.db.models.signals import post_save,post_delete,pre_save
from django.dispatch import receiver
from django_gamification.models import PointChange, Unlockable, \
    GamificationInterface, BadgeDefinition, Badge, UnlockableDefinition,Progression,Category
from django.db.models import F
from ckeditor.fields import RichTextField
import random
from ckeditor_uploader.fields import RichTextUploadingField
def random_id(length):
    CHARACTERS = 'abcdefghijklmnopqrstuvwxyz0123456789'
    return ''.join(random.choice(CHARACTERS) for _ in range(length))

def _default_urlid():
    return random_id(Test._meta.get_field('urlid').max_length)

class Catagory(models.Model):
    name = models.CharField(max_length=255)
    CHOICES = (
        ('N1', 'N1'),
        ('N2', 'N2'),
        ('N3','N3'),
        ('N4','N4'),
        ('N5','N5'),
    )
    level = models.CharField(max_length=10,choices=CHOICES,null=True,blank=True)
    # image = models.ImageField(upload_to='images/lesson_pics', blank=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('lesson', args=[str(self.id)])


class Lesson(models.Model):
    catagory = models.ForeignKey('Catagory',on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=255)
    description = models.TextField(null= True)

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('lesson-detail', args=[str(self.id)])


class Word(models.Model):
    catagory = models.ForeignKey('Catagory',on_delete=models.SET_NULL, null=True)
    word = models.CharField(max_length=255)
    kanji = models.CharField(max_length=255,null=True,blank=True)
    mean = models.CharField(max_length=255,null=True, blank=True)

    CHOICES = (
        ('V', 'Verb'),
        ('N', 'Noun'),
        ('Adj','Adjective'),
    )
    type = models.CharField(max_length=10,choices=CHOICES,null=True,blank=True)
    lesson = models.ManyToManyField(Lesson)

    def __str__(self):
        """String for representing the Model object."""
        return self.word

class Game(models.Model):
    urlid = models.CharField(max_length=10, unique=True, default=_default_urlid)
    test =  models.ForeignKey('Test', on_delete=models.SET_NULL, null=True, blank= True)
    def get_urlid(self):
        return reverse('test-detail', args=[self.urlid])

class Test(models.Model):
    lesson = models.ForeignKey('Lesson', on_delete=models.SET_NULL, null=True, blank= True)
    kanji_lesson = models.ForeignKey('KanjiLesson', on_delete=models.SET_NULL, null=True, blank= True)
    grammar_lesson = models.ForeignKey('GrammarLesson', on_delete=models.SET_NULL, null=True, blank= True)
    question_num = models.IntegerField()
    name = models.CharField(max_length=50, null= True)
    time = models.IntegerField(default=600)
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('test-detail', args=[str(self.id)])

    def get_test_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('test-detail', args=[str(self.id)])
   



class myUser(AbstractUser):
    avatar = models.ImageField(default='/images/profile_pics/default.jpg', upload_to='images/profile_pics')
    email = models.EmailField(_('email address'))
    interface = models.ForeignKey(GamificationInterface, on_delete=models.CASCADE,null=True)
    badge = models.ForeignKey(Badge, on_delete=models.CASCADE,null=True)
    # Resize the image
    # def save(self):
    #     super().save()
    #
    #     image = Image.open(self.avatar.path)
    #     # To resize the profile image
    #     if image.height > 400 or image.width > 400:
    #         output_size = (400, 400)
    #         image.thumbnail(output_size)
    #         image.save(self.avatar.path)


class TestResult(models.Model):
    user = models.ForeignKey('myUser', on_delete=models.CASCADE)
    test = models.ForeignKey('Test', on_delete=models.CASCADE,null=True,blank=True)
    reading = models.ForeignKey('Reading', on_delete=models.CASCADE,null=True,blank=True)
    listening = models.ForeignKey('Listening', on_delete=models.CASCADE,null=True,blank=True)
    correct_answer_num = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True, blank=True)



class UserTest(models.Model):
    user = models.ForeignKey('myUser', on_delete=models.CASCADE)
    test = models.ForeignKey('Test', on_delete=models.CASCADE)
    is_paused = models.BooleanField(default=False)
    remain_time = models.IntegerField(default=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        unique_together = (("user", "test"),)

    def __str__(self):
        """String for representing the Model object."""
        return self.test.name





class UserWord(models.Model):
    user = models.ForeignKey('myUser', on_delete=models.CASCADE)
    word = models.ForeignKey('Word', on_delete=models.CASCADE)
    memoried = models.BooleanField(null=False,default=False)
    date = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.user} - {self.word}'

    class Meta:
        unique_together = (("user", "word"),)

class GrammarLevel(models.Model):
    name = models.CharField(max_length=255)
    CHOICES = (
        ('N1', 'N1'),
        ('N2', 'N2'),
        ('N3','N3'),
        ('N4','N4'),
        ('N5','N5'),
    )
    level = models.CharField(max_length=2,choices=CHOICES,null=True,blank=True)
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('grammar-lesson', args=[str(self.id)])

class GrammarLesson(models.Model):
    name = models.CharField(max_length=255)
    grammar_level = models.ForeignKey(GrammarLevel, on_delete=models.CASCADE)
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('grammar-detail', kwargs={'pk':self.id,'grammar_lesson_id': self.grammar_level.id})

class Grammar(models.Model):
    name = models.CharField(max_length=255)
    connect = models.CharField(max_length=255,default="ALL")
    grammar_lesson = models.ForeignKey(GrammarLesson, on_delete=models.CASCADE)
    def __str__(self):
        """String for representing the Model object."""
        return self.name

class GrammarMean(models.Model):
    mean = models.CharField(max_length=255)
    grammar = models.ForeignKey(Grammar, on_delete=models.CASCADE)

class Example(models.Model):
    example = models.CharField(max_length=255)
    grammar_mean = models.ForeignKey(GrammarMean, on_delete=models.CASCADE)

class KanjiLevel(models.Model):
    name = models.CharField(max_length=255)
    CHOICES = (
        ('N1', 'N1'),
        ('N2', 'N2'),
        ('N3','N3'),
        ('N4','N4'),
        ('N5','N5'),
    )
    level = models.CharField(max_length=2,choices=CHOICES,null=True,blank=True)
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('kanji-lesson', args=[str(self.id)])

class KanjiLesson(models.Model):
    name = models.CharField(max_length=255)
    kanji_level = models.ForeignKey(KanjiLevel, on_delete=models.CASCADE)
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('kanji-detail', kwargs={'pk':self.id,'kanji_lesson_id': self.kanji_level.id})

class Kanji(models.Model):
    kanji = models.CharField(max_length=255)
    reading = models.CharField(max_length=255)
    definition = models.CharField(max_length=255)
    kanji_lesson = models.ForeignKey(KanjiLesson, on_delete=models.CASCADE)
    def __str__(self):
        """String for representing the Model object."""
        return self.kanji
    


class ExampleKanji(models.Model):
    example = models.CharField(max_length=255)
    reading = models.CharField(max_length=255)
    definition = models.CharField(max_length=255)
    kanji = models.ForeignKey(Kanji, on_delete=models.CASCADE)
    

class ReadingLevel(models.Model):
    name = models.CharField(max_length=255)
    CHOICES = (
        ('N1', 'N1'),
        ('N2', 'N2'),
        ('N3','N3'),
        ('N4','N4'),
        ('N5','N5'),
    )
    level = models.CharField(max_length=2,choices=CHOICES,null=True,blank=True)
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""

memory/templates/memory/game.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Memory Game</title>
<style>
.card {
	width: 140px; 
	height: 140px; 
	background-color: transparent;
	background-image: url({% static 'memory/cards_alphabet.png' %}); 
	
}
.cardcell {
	width: 150px; 
	height: 150px; 
}
</style>
<script src="{% static 'memory/gamen.js' %}"></script>
</head>
<body onload="main()" style="margin-left: 30%;">

<p ><h3 style="margin-left: 20%;">This is game {{ game }}.</h3></p>

{% if game.state == 0 %} 
<p >Please wait for other player</p>
<p >Send him this link to join: <a href="{{ game.get_absolute_url }}">{{ game.get_absolute_url }}</a></p>

{% else %}
{% if player %}
<p>You are {{ player }}.</p>
{% endif %}
<table>
<tr>
{% for aplayer in game.players.all %}
<td id="player{{ aplayer.id }}" {% if aplayer.is_current_player %}style="background: yellow "{% endif %}>{{ aplayer.name }} - {{ aplayer.score }}</td>
{% endfor %}
</tr>
</table>


<p id="message">{{game.message}}</p>

<form method='post' id="game-form">
{% csrf_token %}
<div id="ended" {% if not game.has_ended  %} style="visibility: hidden" {% endif %}>
<p><input type="submit" value="Play again"/></p>
<p><a href="{% url 'memory:welcome' %}">or start a new game with somebody else.</a></p>
</div>
<table>
{% for card in game.cards.all %}
    {% if forloop.counter0|divisibleby:4 %}<tr>{% endif %}
	<td class="cardcell">
	{% if card.shown %}
		<button type="submit" name="card" value="{{ card.id }}" class="card" id="card{{card.id}}"></button>
	{% elif card.visible %}
		<button type="submit" name="card" value="{{ card.id }}" class="card" id="card{{card.id}}"></button>
	{% else %}
		<button type="submit" name="card" value="{{ card.id }}" class="card" id="card{{card.id}}" style="visibility: hidden"></button>
	{% endif %}
	</td>
    {% if forloop.counter|divisibleby:4 %}</tr>{% endif %}
{% endfor %}
</table>
</form>
{% endif %}
</body>
</html>

memory/templates/memory/join.html
<p>Welcome to the Memory game</p>
<form method="post">
{% csrf_token %}
{% if request.user.username %}
<label for="name">Your name or nickname</label><input type="text" name="name" value="{{request.user.username}}" readonly="readonly"/>
<input type="submit" value="Join the game"/> 
</form>
{%else%}
<div class="login_button "><a href="{% url 'login' %}?next={{request.path}}">Sign in</a></div>
{%endif%}
<p>{{ error }}</p>

memory/templates/memory/newgame.html
{% extends "base_generic.html" %}
{% load static %}
{% load widget_tweaks %}
{% load i18n %}
{% block content%}
<h1 style="margin-top: 200px;margin-left: 25%;">Welcome to the Memory game</h1>

{% if request.user.username %}


<p>{{ error }}</p>
<p style="margin-left: 25px;"><strong> you want to join an existing game please ask the link from the other player. Or you can choose lesson and create new game</strong></p>
<div class="col-md-3">
    <select class="nav-link dropdown-toggle form-select" id="filter-list" onchange="openCity()"
            role="button" aria-haspopup="true" aria-expanded="false">
            <option>Choose</option>
        <optgroup label="{% trans 'Vocabulary' %}">
            
            {%for category in category%}
            <option>{{category}}</option>
            {%endfor%}            
        </optgroup>
        <optgroup label="{% trans 'Kanji' %}">
            {%for kanjilesson in kanjilevel%}
            <option>Kanji{{kanjilesson}}</option>
            {%endfor%}            
        </optgroup>
    </select>
</div>
<br>
{% for category in category %}
<div id="{{category}}" class="row courses_row city" style="display: none">

    {% for lesson in category.lesson_set.all %}
        <form method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <label class="col-md-3" for="name" style="margin-left: 50px;"><strong>Lesson:{{lesson.name}}</strong></label>
            <input type="text" name="name" value="{{request.user}}" readonly="readonly" style="display: none;"/>
            <input type="text" name="lesson" value="{{lesson.id}}" readonly="readonly" style="display: none;"/>
            <input class="col-md-3" type="submit" value="Start a new game"/> 
        </div>
        </form>
    {% endfor %}
</div>

{%endfor%}
{% for kanjilv in kanjilevel %}
<div id="Kanji{{kanjilv}}" class="row courses_row city" style="display: none">

    {% for lesson in kanjilv.kanjilesson_set.all %}
        <form method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <label class="col-md-3" for="name" style="margin-left: 50px;"><strong>Lesson:{{lesson.name}}</strong></label>
            <input type="text" name="name" value="{{request.user}}" readonly="readonly" style="display: none;"/>
            <input type="text" name="kanjilesson" value="{{lesson.id}}" readonly="readonly" style="display: none;"/>
            <input  class="col-md-3" type="submit" value="Start a new game"/> 
        </div>
        </form>
    {% endfor %}
</div>

{%endfor%}
<br>
{%else%}
<div class="login_button "><a href="{% url 'login' %}?next={% url 'index' %}">Sign in</a></div>
{%endif%}
{%endblock%}
{% block javascript %}
<script>
    function openCity() {
        var i;
        var x = document.getElementsByClassName("city");
        var cityName = document.getElementById("filter-list").value
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        document.getElementById(cityName).style.display = "block";
    }
</script>
{% endblock %}