elearning/urls.py
from django.contrib import admin
from django.urls import path
# Use include() to add paths from the catalog application 
from django.urls import include
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from gogoedu.views import change_language
import notifications.urls
import notifications_rest.urls
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views


urlpatterns = [
    path('change_language/', change_language, name='change_language'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('gogoedu/', include('gogoedu.urls')),
    path('memory/', include('memory.urls')),
    path('', RedirectView.as_view(url='gogoedu/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notifications/', include('notifications_rest.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
    prefix_default_language=False,
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

gogoedu/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('register/', views.register, name='register'),
	path('profile/<int:pk>', views.Profile.as_view(), name='profile-detail'),
	path('password/', views.change_password, name='change_password'),
	path('lesson/<int:pk>', views.Lesson_detail.as_view(), name='lesson-detail'),
	path('lesson/<int:pk>/flashcard', views.viewflashcard, name='lesson-flashcard'),
	path('lesson/<int:pk>/tests/', views.GetTestInfo.as_view(), name='lesson-tests'),
	path('lesson/<int:pk>/words/<int:wordid>/learned/', views.MarkLearned.as_view(), name='mark-learned'),
	path('catagory/', views.CatagoryListView.as_view(), name='catagory'),
	path('catagory/<int:pk>', views.CatagoryDetailView.as_view(), name='lesson'),
	path('grammar/', views.GrammarLevelListView.as_view(), name='grammar'),
	path('grammar/<int:pk>', views.GrammarLevelDetailView.as_view(), name='grammar-lesson'),
	path('grammar/<int:grammar_lesson_id>/lesson/<int:pk>', views.Grammar_lesson_detail.as_view(), name='grammar-detail'),
	path('lesson/<int:pk>/grammar/<int:wordid>/learned/', views.MarkLearnedGrammar.as_view(), name='mark-learned-grammar'),
	path('kanji/', views.KanjiLevelListView.as_view(), name='kanji'),
	path('kanji/<int:pk>', views.KanjiLevelDetailView.as_view(), name='kanji-lesson'),
	path('kanji/<int:kanji_lesson_id>/lesson/<int:pk>', views.Kanji_lesson_detail.as_view(), name='kanji-detail'),
	path('lesson/<int:pk>/kanjis/<int:wordid>/learned/', views.MarkLearnedKanji.as_view(), name='mark-learned-kanji'),
	path('kanji/<int:pk>/flashcard', views.viewkanjiflash, name='kanji-flashcard'),
	path('kanji/<int:pk>/flashcard/game', views.kanjiflashcard_test, name='kanji-flashcard-game'),
	path('reading/', views.ReadingLevelListView.as_view(), name='reading'),
	path('reading/<int:pk>', views.ReadingLevelDetailView.as_view(), name='reading-lesson'),
	path('reading/<int:reading_lesson_id>/lesson/<int:pk>', views.Reading_lesson_detail.as_view(), name='reading-detail'),
	path('listening/', views.ListeningLevelListView.as_view(), name='listening'),
	path('listening/<int:pk>', views.ListeningLevelDetailView.as_view(), name='listening-lesson'),
	path('listening/<int:listening_lesson_id>/lesson/<int:pk>', views.Listening_lesson_detail.as_view(), name='listening-detail'),
	path('profile/<int:pk>/edit', views.profile_update, name='profile-update'),
	path('test/<int:pk>', views.test_detail_view, name='test-detail'),
	path('test/<int:pk>/paused', views.TestPause.as_view(), name='test-paused'),
	path('test/<int:pk>/saved', views.TestSave.as_view(), name='test-saved'),
	path('results/<int:pk>', views.show_form_correct, name='show_results'),
	path('reading/results/<int:pk>', views.show_form_correct_reading, name='show_results_reading'),
	path('listening/results/<int:pk>', views.show_form_correct_listening, name='show_results_listening'),
	path('activate/<uidb64>/<token>', views.activate, name='activate'),
	path('register/<int:pk>/activation', views.activation_request, name='account-activation'),
	path('summary/', views.summary_detail_view, name='show_summary'),
	path('summary/chart/', views.ChartData.as_view()),
	path('flashcard/', views.flashcard_view, name='flashcard'),
	path('leaderboard/', views.leaderboard_view, name='leaderboard'),
	path('privacy/', views.privacy_view, name='privacy'),
	path('flashcard/<int:pk>', views.view_card_set, name = 'view_card_set'), 
	path('flashcard/<int:pk>/test', views.flashcard_test, name = 'flashcard_test'), 
	path('badge', views.BadgeView.as_view(), name='badge'),
    path('badge/award-badge/<int:badge_id>/', views.AwardBadgeView.as_view(), name='award-badge'),
    path('badge/revoke-badge/<int:badge_id>/', views.RevokeBadgeView.as_view(), name='revoke-badge'),
	path('profile/<int:pk>/<int:badge_id>/', views.SetBadgeView.as_view(), name='set-badge'),
	path('alphabet', views.alphabet, name='alphabet'),
	path('mission/', views.MissionView.as_view()),
	path('alphabet/getfinish', views.CheckAlphabet.as_view()),
	path('listtest/', views.listtest, name='listtest'),
	path('message/',views.message,name='message'),
	path('todo/',views.todolist, name='todo'),	
	path('new-todo/', views.new_todo, name="new_todo"),
    path('mark-as-done/<int:id>', views.mark_as_done, name="mark_as_done"),
]

memory/urls.py
from django.conf.urls import url

from . import views

app_name = 'memory'
urlpatterns = [
    url(r'^$', views.Welcome.as_view(), name='welcome'),
    url(r'^(?P<urlid>[0-9a-z]+)/$', views.GameView.as_view(), name='game'),
    url(r'^(?P<urlid>[0-9a-z]+)/json$', views.GameViewJSON.as_conditional_view(), name='game_json'),
]

gogoedu/models.py
from os import name
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.db.models.fields import BooleanField
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from PIL import Image
from django.utils import timezone
import datetime
from notifications.signals import notify
from django.db.models.signals import post_save,post_delete,pre_save
from django.dispatch import receiver
from django_gamification.models import PointChange, Unlockable, \
    GamificationInterface, BadgeDefinition, Badge, UnlockableDefinition,Progression,Category
from django.db.models import F
from ckeditor.fields import RichTextField
import random
from ckeditor_uploader.fields import RichTextUploadingField
def random_id(length):
    CHARACTERS = 'abcdefghijklmnopqrstuvwxyz0123456789'
    return ''.join(random.choice(CHARACTERS) for _ in range(length))

def _default_urlid():
    return random_id(Test._meta.get_field('urlid').max_length)

class Catagory(models.Model):
    name = models.CharField(max_length=255)
    CHOICES = (
        ('N1', 'N1'),
        ('N2', 'N2'),
        ('N3','N3'),
        ('N4','N4'),
        ('N5','N5'),
    )
    level = models.CharField(max_length=10,choices=CHOICES,null=True,blank=True)
    # image = models.ImageField(upload_to='images/lesson_pics', blank=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('lesson', args=[str(self.id)])


class Lesson(models.Model):
    catagory = models.ForeignKey('Catagory',on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=255)
    description = models.TextField(null= True)

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('lesson-detail', args=[str(self.id)])


class Word(models.Model):
    catagory = models.ForeignKey('Catagory',on_delete=models.SET_NULL, null=True)
    word = models.CharField(max_length=255)
    kanji = models.CharField(max_length=255,null=True,blank=True)
    mean = models.CharField(max_length=255,null=True, blank=True)

    CHOICES = (
        ('V', 'Verb'),
        ('N', 'Noun'),
        ('Adj','Adjective'),
    )
    type = models.CharField(max_length=10,choices=CHOICES,null=True,blank=True)
    lesson = models.ManyToManyField(Lesson)

    def __str__(self):
        """String for representing the Model object."""
        return self.word

class Game(models.Model):
    urlid = models.CharField(max_length=10, unique=True, default=_default_urlid)
    test =  models.ForeignKey('Test', on_delete=models.SET_NULL, null=True, blank= True)
    def get_urlid(self):
        return reverse('test-detail', args=[self.urlid])

class Test(models.Model):
    lesson = models.ForeignKey('Lesson', on_delete=models.SET_NULL, null=True, blank= True)
    kanji_lesson = models.ForeignKey('KanjiLesson', on_delete=models.SET_NULL, null=True, blank= True)
    grammar_lesson = models.ForeignKey('GrammarLesson', on_delete=models.SET_NULL, null=True, blank= True)
    question_num = models.IntegerField()
    name = models.CharField(max_length=50, null= True)
    time = models.IntegerField(default=600)
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('test-detail', args=[str(self.id)])

    def get_test_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('test-detail', args=[str(self.id)])
   



class myUser(AbstractUser):
    avatar = models.ImageField(default='/images/profile_pics/default.jpg', upload_to='images/profile_pics')
    email = models.EmailField(_('email address'))
    interface = models.ForeignKey(GamificationInterface, on_delete=models.CASCADE,null=True)
    badge = models.ForeignKey(Badge, on_delete=models.CASCADE,null=True)
    # Resize the image
    # def save(self):
    #     super().save()
    #
    #     image = Image.open(self.avatar.path)
    #     # To resize the profile image
    #     if image.height > 400 or image.width > 400:
    #         output_size = (400, 400)
    #         image.thumbnail(output_size)
    #         image.save(self.avatar.path)


class TestResult(models.Model):
    user = models.ForeignKey('myUser', on_delete=models.CASCADE)
    test = models.ForeignKey('Test', on_delete=models.CASCADE,null=True,blank=True)
    reading = models.ForeignKey('Reading', on_delete=models.CASCADE,null=True,blank=True)
    listening = models.ForeignKey('Listening', on_delete=models.CASCADE,null=True,blank=True)
    correct_answer_num = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True, blank=True)



class UserTest(models.Model):
    user = models.ForeignKey('myUser', on_delete=models.CASCADE)
    test = models.ForeignKey('Test', on_delete=models.CASCADE)
    is_paused = models.BooleanField(default=False)
    remain_time = models.IntegerField(default=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        unique_together = (("user", "test"),)

    def __str__(self):
        """String for representing the Model object."""
        return self.test.name





class UserWord(models.Model):
    user = models.ForeignKey('myUser', on_delete=models.CASCADE)
    word = models.ForeignKey('Word', on_delete=models.CASCADE)
    memoried = models.BooleanField(null=False,default=False)
    date = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.user} - {self.word}'

    class Meta:
        unique_together = (("user", "word"),)

class GrammarLevel(models.Model):
    name = models.CharField(max_length=255)
    CHOICES = (
        ('N1', 'N1'),
        ('N2', 'N2'),
        ('N3','N3'),
        ('N4','N4'),
        ('N5','N5'),
    )
    level = models.CharField(max_length=2,choices=CHOICES,null=True,blank=True)
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('grammar-lesson', args=[str(self.id)])

class GrammarLesson(models.Model):
    name = models.CharField(max_length=255)
    grammar_level = models.ForeignKey(GrammarLevel, on_delete=models.CASCADE)
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('grammar-detail', kwargs={'pk':self.id,'grammar_lesson_id': self.grammar_level.id})

class Grammar(models.Model):
    name = models.CharField(max_length=255)
    connect = models.CharField(max_length=255,default="ALL")
    grammar_lesson = models.ForeignKey(GrammarLesson, on_delete=models.CASCADE)
    def __str__(self):
        """String for representing the Model object."""
        return self.name

class GrammarMean(models.Model):
    mean = models.CharField(max_length=255)
    grammar = models.ForeignKey(Grammar, on_delete=models.CASCADE)

class Example(models.Model):
    example = models.CharField(max_length=255)
    grammar_mean = models.ForeignKey(GrammarMean, on_delete=models.CASCADE)

class KanjiLevel(models.Model):
    name = models.CharField(max_length=255)
    CHOICES = (
        ('N1', 'N1'),
        ('N2', 'N2'),
        ('N3','N3'),
        ('N4','N4'),
        ('N5','N5'),
    )
    level = models.CharField(max_length=2,choices=CHOICES,null=True,blank=True)
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('kanji-lesson', args=[str(self.id)])

class KanjiLesson(models.Model):
    name = models.CharField(max_length=255)
    kanji_level = models.ForeignKey(KanjiLevel, on_delete=models.CASCADE)
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('kanji-detail', kwargs={'pk':self.id,'kanji_lesson_id': self.kanji_level.id})

class Kanji(models.Model):
    kanji = models.CharField(max_length=255)
    reading = models.CharField(max_length=255)
    definition = models.CharField(max_length=255)
    kanji_lesson = models.ForeignKey(KanjiLesson, on_delete=models.CASCADE)
    def __str__(self):
        """String for representing the Model object."""
        return self.kanji
    


class ExampleKanji(models.Model):
    example = models.CharField(max_length=255)
    reading = models.CharField(max_length=255)
    definition = models.CharField(max_length=255)
    kanji = models.ForeignKey(Kanji, on_delete=models.CASCADE)
    

class ReadingLevel(models.Model):
    name = models.CharField(max_length=255)
    CHOICES = (
        ('N1', 'N1'),
        ('N2', 'N2'),
        ('N3','N3'),
        ('N4','N4'),
        ('N5','N5'),
    )
    level = models.CharField(max_length=2,choices=CHOICES,null=True,blank=True)
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""

gogoedu/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from gogoedu.models import myUser
from django.utils.translation import gettext as _


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=150, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=255, required=True)
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        # help_text=password_validation.password_validators_help_text_html(),
    )

    class Meta:
        model = myUser
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]

    def clean(self):
        email = self.cleaned_data.get('email')
        if myUser.objects.filter(email=email):
            raise forms.ValidationError(_("Email existed. Please try again"))
        return self.cleaned_data


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = myUser
        fields = ["first_name", "last_name",  "avatar"]
        exclude = ['user']

gogoedu/templates/gogoedu/change_password.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/myuser_profile.css' %}">
{% endblock %}

{% block content %}
<div class="home">
    <div class="container emp-profile" style="margin-top: 200px">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                
            </div>
            <div class="col-md-8">
                <form class="counter_form_content d-flex flex-column" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit">Save changes</button>
                  </form>
                
            </div>
        </div>
    </div>
</div>
{% endblock %}

gogoedu/templates/gogoedu/kanjilevel_detail.html
{% extends "gogoedu/kanjilevel_list.html" %}
{% load i18n %}
{%block searchform%}
	<form action="" method="get" id="courses_search_form" class="courses_search_form d-flex flex-row align-items-center justify-content-start">
		<input type="search" class="courses_search_input" placeholder="{% trans 'Search Lesson'%}"  name ='name' value="{{ request.GET.name }}">
		<input type="submit" value="{% trans 'Search' %}" class="courses_search_button ml-auto" />
	</form> 
{% endblock %}
{% block home %}
	<div class="home">
		<div class="breadcrumbs_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="breadcrumbs">
							<ul>
								<li><a href="{% url 'index' %}">{% trans 'Home' %}</a></li>
								<li><a href="{% url 'kanji' %}">{% trans 'Kanji' %}</a></li>
								<li>{{ kanji.name }}</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{% block content2 %}
{% if object_list %}
<div class="container mt-5 mb-5">

<h3>{{kanji_lesson.name}}</h3>
 <div class="list-group mt-3">
  {% for kanji_lesson in object_list %}
  <a class="progress" href="{{ kanji_lesson.get_absolute_url }}">
	<a class="list-group-item" href="{{ kanji_lesson.get_absolute_url }}"><i class="fa fa-book fa-fw" aria-hidden="true"></i>&nbsp; {{kanji_lesson.name}}</a>
	<div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{kanji_lesson.percent}}%" aria-valuenow="{{kanji_lesson.percent}}" aria-valuemin="0" aria-valuemax="100">{{kanji_lesson.percent|floatformat}}%</div>
  </a>
  {% endfor %}
</div>

</div>
{% else %}
	<p>NO KanjiLesson.</p>
{% endif %}

{% endblock %}

gogoedu/templates/gogoedu/listeninglesson_detail.html
{% extends "base_generic.html" %}
{% load static %}
{% load i18n %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'plugins/colorbox/colorbox.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/lesson.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/course_responsive.css' %}">
{% endblock %}

{% block content %}

<!-- Home -->

<div class="home">
    <div class="breadcrumbs_container">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="breadcrumbs">
                        <ul>
                            <li><a href="{% url 'index' %}">{% trans 'Home' %}</a></li>
                            <li><a href="{% url 'listening' %}">{% trans 'Listening' %}</a></li>
                            <li><a href="{% url 'listening-lesson' listeninglesson.listening_level.id%}">{{listeninglesson.listening_level.name}}</a></li>
                            <li>{{listeninglesson.name}}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="course">
    <div class="container">
        <div class="row">

            <!-- Course -->
            <div class="col-lg-8">
                <div class="course_container">
                    <div id="lessonName" data-id="{{listeninglesson.id}}" class="course_title">{% trans 'Lesson' %}:
                        {{listeninglesson.name}}
                    </div>

                    <div class="course_info d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start">

                        <!-- Course Info Item -->
                        <div class="course_info_item">
                            <div class="course_info_title">{% trans 'listening Level' %}</div>
                            <div class="course_info_text"><a href="#">{{listeninglesson.listening_level}}</a></div>
                        </div>

                    </div>

                    <!-- Course Image -->
                    <!-- <div class="course_image"><img src="{% static 'images/course_image.jpg'%}" alt=""></div> -->

                    <!-- Course Tabs -->
                    <div class="course_tabs_container">
                        <div class="tabs d-flex flex-row align-items-center justify-content-start">
                            <!-- <div class="tab">
                                {% trans 'Text' %}
                            </div> -->
                            <div class="tab active">
                                {% trans 'listening' %}
                            </div>
                            <!-- <div class="tab">
                                {% trans 'Test' %}
                            </div> -->
                        </div>
                        <div class="tab_panels">

                            <!-- Description -->
                            <!-- <div class="tab_panel">
                                {% for listening in object_list %}<div class="tab_panel_title">{{listening.text|safe}}</div>
                               {%endfor%}
                            </div> -->

                            <!-- Curriculum -->
                            <div class="tab_panel tab_panel_2 active">
                                <div class="tab_panel_content">
                                    <div class="row">
                                        <div class="tab_panel_title col-md-9">{{listeninglesson.name}}</div>
                                    </div>
                                    <div id="wordListTab" class="tab_panel_content">
                                        <div id="All" class="w3-container city">
                                            {% for listening in object_list %}
                                            <audio src="{{ listening.file.url }}" controls></audio> 
                                            <form class="mt-5" action="" method="POST" id="quiz" data-id="{{test.id}}">
                                                {% csrf_token %}
                                                <ol>
                                                {%for question in listening.question_set.all%}
                                                <li style="font-size: 1.2rem;">
                                                    {{question.question|safe}}
                                                    {% for choice in question.choice_set.all %}
                                                    <label class="radio" for="">
                                                        <input type="radio"
                                                               class="choice-input"
                                                               value="{{ choice.id }}"
                                                               name="question-{{ question.id }}"
                                                        >
                                                        {{choice}}
                                                    </label>
                                                    <br>
                                                    {% endfor %}
                                                </li>
                                                {% endfor %}
                                                </ol>
                                                <div class="row mt-5 d-flex justify-content-between">
                                                    <input type="submit" class="btn btn-primary" value="{% trans 'Submit'%}">
                                                </div>
                                            </form>
                                                        
                                            {% endfor %}
                                            
                                        </div>
										
										
										{% block pagination %}
										{% if is_paginated %}
										<div class="pagination">
											<span class="page-links">
												{% if page_obj.has_previous %}
												<a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
												{% endif %}
												<span class="page-current">
													Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
												</span>
												{% if page_obj.has_next %}
												<a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
												{% endif %}
											</span>
										</div>
										{% endif %}
										{% endblock %}
                                        
                                    </div>
                                </div>
                            </div>

                            
                        </div>
                    </div>
                </div>

                <!-- Course Sidebar -->
                <div class="col-lg-4">
                    <div class="sidebar">

                        <!-- Feature -->
                        <div class="sidebar_section">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Newsletter -->

<div class="newsletter">
    <div class="newsletter_background"
         style="background-image:url({% static 'images/newsletter_background.jpg' %})"></div>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="newsletter_container d-flex flex-lg-row flex-column align-items-center justify-content-start">

                    <!-- Newsletter Content -->
                    <div class="newsletter_content text-lg-left text-center">
                        <div class="newsletter_title">{% trans 'sign up for news and offers' %}</div>
                        <div class="newsletter_subtitle">{% trans 'Subcribe to lastest smartphones news & great deals we offer' %}                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block plugin %}
<script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
<script src="{% static 'styles/bootstrap4/popper.min.js'%}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js'%}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js'%}"></script>
<script src="{% static 'plugins/easing/easing.js'%}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js'%}"></script>
<script src="{% static 'plugins/colorbox/jquery.colorbox-min.js'%}"></script>
<script src="{% static 'js/course.js'%}"></script>
{% endblock %}

gogoedu/templates/gogoedu/listtest.html
{% extends "gogoedu/catagory_list.html" %}
{% load i18n %}
{%block searchform%}
	<form action="" method="get" id="courses_search_form" class="courses_search_form d-flex flex-row align-items-center justify-content-start">
		<input type="search" class="courses_search_input" placeholder="{% trans 'Search Lesson'%}"  name ='name' value="{{ request.GET.name }}">
		<input type="submit" value="{% trans 'Search' %}" class="courses_search_button ml-auto" />
	</form> 
{% endblock %}

{% block content2 %}
{% if test %}
<div class="container mt-5 mb-5">


 <div class="list-group mt-3">
  {% for test in test %}
 
	<div class="list-group-item" ><i class="fa fa-book fa-fw" aria-hidden="true"></i>&nbsp; {{test.name}}</div>
	<a href="{{ test.get_absolute_url }}">Do test</a>

    <form method="post">
        {% csrf_token %}
        
        <input type="submit" value="Play with friends"/> 
    </form>
  
  {% endfor %}
</div>

</div>
{% else %}
	<p>NO Test.</p>
{% endif %}

{% endblock %}